# NumPy


In [1]:
import numpy as np


In [9]:
a=np.array([1,2,3]) #One dimensional array
a

array([1, 2, 3])

In [3]:
b = np.array([[1,2,3],[2,3,4]])
b

array([[1, 2, 3],
       [2, 3, 4]])

In [4]:
#Get dimension 
a.ndim

1

In [5]:
b.ndim


2

In [6]:
#Get shape
a.shape

(3,)

In [7]:
b.shape

(2, 3)

In [8]:
# Get type
a.dtype

dtype('int64')

In [11]:
#If we want to specify data type 
a=np.array([1,2,3],dtype='int16') 
a.dtype


dtype('int16')

In [16]:
# Get size
a.itemsize

2

In [18]:
# Total size
a.nbytes

6

In [22]:
#Accessing/ changing specific elements, rows, columns etc
a = np.array([[5,6,7,8,9],[10,45,2,5,8]])
a

array([[ 5,  6,  7,  8,  9],
       [10, 45,  2,  5,  8]])

In [23]:
# Get a specific elements [row, column] start from 0a
a[1,2]

np.int64(2)

In [24]:
#Get a specific row
a[0, :]

array([5, 6, 7, 8, 9])

In [25]:
#Get specific coumns
a[:, 3]

array([8, 5])

In [26]:
#Getting sequence [start index:endindex:stepsize]
a[0, 1: 4:1]

array([6, 7, 8])

In [27]:
#Change the element
a[1,3]=20
a

array([[ 5,  6,  7,  8,  9],
       [10, 45,  2, 20,  8]])

In [29]:
#3d example
b= np.array([[[1,2],[3,4]],[[5,6],[9,8]]])
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [9, 8]]])

In [30]:
# Get specific elements
b[0,1,0]

np.int64(3)

In [32]:
#Repacing specific element
b[0,1,1]=10
b

array([[[ 1,  2],
        [ 3, 10]],

       [[ 5,  6],
        [ 9,  8]]])

### Initialize Different Types of Arrays


In [35]:
#All zeros matrix
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [36]:
#All ones matrix
np.ones((4,2,3))

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [37]:
#All other number
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [40]:
#Random decimal numbers
np.random.rand(2,2)


array([[0.38099797, 0.7206523 ],
       [0.5077841 , 0.2171639 ]])

In [42]:
#Random integer matrix
np.random.randint(7,size=(3,3))

array([[5, 1, 5],
       [0, 6, 5],
       [6, 1, 4]])

In [43]:
#The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [46]:
#Repeat the array
arr= np.array([[1,2,3]])
r=np.repeat(arr,3,axis=0)
r

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [58]:
#Print an given array 
a=np.ones((5,5),dtype='int')
z=np.zeros((3,3))
a[1:4,1:4]=z
a[2,2]=9
a

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 9, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

In [59]:
#Copying an array
a= np.array([1,2,3])
b=a
b[0]=100
a 

array([100,   2,   3])

In [61]:
#In above example of copying an array the change in b also change the a. So be careful while copying the array (use copy()function)
a= np.array([1,2,3])
b=a.copy()
b[0]=100
a

array([1, 2, 3])

## Mathematics 

In [72]:
a= np.array([1,2,3])
a+7

array([ 8,  9, 10])

In [73]:
a-2

array([-1,  0,  1])

In [74]:
a*2

array([2, 4, 6])

In [75]:
a/5

array([0.2, 0.4, 0.6])

In [76]:
a**2

array([1, 4, 9])

In [77]:
b =np.array([5,2,4])

In [78]:
a+b

array([6, 4, 7])

## linear algebra

In [81]:
#Matrix multiplication
a = np.ones ((2,3))
print(a)
b=np.ones((3,4))
print(b)
np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


array([[3., 3., 3., 3.],
       [3., 3., 3., 3.]])

In [84]:
#Find determinant 
c= np.identity(3)
print(c)
np.linalg.det(c)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


np.float64(1.0)

##### Statistics

In [85]:
stat = np.array([[5,9,6],[1,2,3]])
stat

array([[5, 9, 6],
       [1, 2, 3]])

In [86]:
np.min(stat)

np.int64(1)

In [87]:
np.max(stat)

np.int64(9)

In [88]:
np.sum(stat)

np.int64(26)

### Reorganizing arrays

In [91]:
before = np.array([[5,2,8],[7,4,1]])
print(before)
after= before.reshape((1,6))
print(after)

[[5 2 8]
 [7 4 1]]
[[5 2 8 7 4 1]]


In [93]:
#Vertically stacking vectors
v1= np.array([1,2,3,4])
v2=np.array([5,6,4,2])
np.vstack([v1,v2,v2])

array([[1, 2, 3, 4],
       [5, 6, 4, 2],
       [5, 6, 4, 2]])

In [94]:
#Horizontal stacking vectors
v1= np.array([1,2,3,4])
v2=np.array([5,6,4,2])
np.hstack([v1,v2,v1])

array([1, 2, 3, 4, 5, 6, 4, 2, 1, 2, 3, 4])